Feature/b 68 privacy issues
jst-seminar-rostlab-tum/genomics.ai pull request #185
Opened 2022-05-24 09:30 UTC by AlphaGergedan

Sensitive fields remove from the response of the route `/users/:id`

2022-05-24 09:49 UTC, FabianNowak approved these changes
Are there any other routes which return the full users?

2022-05-24 09:52 UTC, FabianNowak requested changes

2022-05-24 09:52 UTC, FabianNowak commented on Backend/src/API/REST/routes/user/userRouter.ts
> +        ...filtered_user} = await UserService.getUserById(user_id);
```suggestion
        ...filtered_user} = await UserService.getUserById(user_id) || {};
```
Destrucutring of user will crash if user is null/undefined

2022-05-25 10:47 UTC, AlphaGergedan commented
> Are there any other routes which return the full users?

No, this was the only route.

2022-05-25 10:53 UTC, FabianNowak approved these changes

2022-05-26 13:05 UTC, merged